name: BUILD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [3.0, 3.1, 3.3]

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Install libraries
      run: |
        sudo apt-get install -y libpq-dev postgresql-client

    - name: Configure database
      env:
        PGPASSWORD: postgres
        PGUSER: postgres
        PGHOST: localhost
      run: |
        echo "Configuring PostgresSQL"
        psql -c 'create database "array_enum_test";'

    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name : Ruby Setup
      uses: ruby/setup-ruby@v1.173.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Run test
      env:
        PGPASSWORD: postgres
        PGUSER: postgres
        PGHOST: localhost
      run: bundle exec rake -s test
